#include <gtk/gtk.h>
static void load_css(void) {
    GtkCssProvider *provider;
    GdkDisplay *display;
    GdkScreen *screen;
    const gchar *css_style_file = "style.css";
    GFile *css_fp               = g_file_new_for_path(css_style_file);
    GError *error               = 0;
    provider = gtk_css_provider_new();
    display = gdk_display_get_default();
    screen = gdk_display_get_default_screen(display);
    gtk_style_context_add_provider_for_screen(screen, GTK_STYLE_PROVIDER(provider), GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
    gtk_css_provider_load_from_file(provider, css_fp, &error);
    g_object_unref(provider);
}
static void activate(GtkApplication *app, gpointer data) {
    GtkWidget *window;
    GtkWidget *containerBox;
    GtkWidget *gridPayment, *vbox;
    GtkWidget *helloLabel, *userReciNameLabel, *addressLabel, *phoneLabel, *paymentLabel, *couponLabel, *totalbillLabel, *discountLabel, *costLabel, *moneyTotal, *moneyDiscount, *moneyCost;
    GtkWidget *buttonBackPayment, *buttonPayment, *buttonPayment2, *buttonCoupon, *buttonOrder;
    GtkWidget *entryReciName, *entryAddress, *entryPhone, *entryCoupon;
    load_css();
    window = gtk_application_window_new(app);
    gtk_window_set_title(GTK_WINDOW(window), "payment");
    gtk_window_set_default_size(GTK_WINDOW(window),500,500);
    gtk_window_set_resizable(GTK_WINDOW(window), FALSE);
    gtk_window_set_position(GTK_WINDOW(window), GTK_WIN_POS_CENTER);
    containerBox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 10);
    helloLabel = gtk_label_new("Hello Customer!");
    userReciNameLabel = gtk_label_new("Recipient's name: ");
    addressLabel = gtk_label_new("Delivery address: ");
    phoneLabel = gtk_label_new("Phone number: ");
    paymentLabel = gtk_label_new("Payment method: ");
    couponLabel = gtk_label_new("Coupon: ");
    totalbillLabel = gtk_label_new("Total bill: ");
    discountLabel = gtk_label_new("Discount: ");
    costLabel = gtk_label_new("Total cost: ");
    moneyTotal = gtk_label_new("$100.00");
    moneyDiscount = gtk_label_new(" - $80.00");
    moneyCost = gtk_label_new("$20.00");
    buttonPayment = gtk_radio_button_new_with_label(NULL, "Cash on delivery");
    buttonPayment2 = gtk_radio_button_new_with_label(gtk_radio_button_get_group(GTK_RADIO_BUTTON(buttonPayment)), "Credit card");
    buttonBackPayment = gtk_button_new_with_label("Back");
    gtk_widget_set_name(buttonBackPayment, "buttonBackPayment");
    buttonCoupon = gtk_button_new_with_label("Add the coupon");
    gtk_widget_set_name(buttonCoupon, "buttonCoupon");
    buttonOrder = gtk_button_new_with_label("ORDER NOW");
    //gtk_button_set_always_show_image (GTK_BUTTON(buttonOrder), TRUE);
    entryReciName = gtk_entry_new();
    gtk_entry_set_icon_from_icon_name(GTK_ENTRY(entryReciName), GTK_ENTRY_ICON_PRIMARY, "contact-new");
    gtk_entry_set_placeholder_text(GTK_ENTRY(entryReciName), "Type your name");
    entryAddress = gtk_entry_new();
    gtk_entry_set_icon_from_icon_name(GTK_ENTRY(entryAddress), GTK_ENTRY_ICON_PRIMARY, "emblem-mail");
    gtk_entry_set_placeholder_text(GTK_ENTRY(entryAddress), "Type your home address");
    entryPhone = gtk_entry_new();
    gtk_entry_set_icon_from_icon_name(GTK_ENTRY(entryPhone), GTK_ENTRY_ICON_PRIMARY, "phone");
    gtk_entry_set_placeholder_text(GTK_ENTRY(entryPhone), "Type your phone number");
    entryCoupon = gtk_entry_new();
    gridPayment = gtk_grid_new();
    gtk_grid_set_row_spacing(gridPayment, 20);
    gtk_grid_set_column_spacing(gridPayment, 20);
    gtk_grid_attach(gridPayment, helloLabel, 0, 0, 1, 1);
    gtk_grid_attach(gridPayment, buttonBackPayment, 2, 0, 1, 1);
    gtk_grid_attach(gridPayment, userReciNameLabel, 0, 1, 1, 1);
    gtk_grid_attach(gridPayment, entryReciName, 1, 1, 2, 1);
    gtk_grid_attach(gridPayment, addressLabel, 0, 2, 1, 1);
    gtk_grid_attach(gridPayment, entryAddress, 1, 2, 2, 1);
    gtk_grid_attach(gridPayment, phoneLabel, 0, 3, 1, 1);
    gtk_grid_attach(gridPayment, entryPhone, 1, 3, 2, 1);
    gtk_grid_attach(gridPayment, paymentLabel, 0, 4, 1, 1);
    gtk_grid_attach(gridPayment, buttonPayment, 1, 4, 1, 1);
    gtk_grid_attach(gridPayment, buttonPayment2, 2, 4, 1, 1);
    gtk_grid_attach(gridPayment, couponLabel, 0, 5, 1, 1);
    gtk_grid_attach(gridPayment, entryCoupon, 1, 5, 1, 1);
    gtk_grid_attach(gridPayment, buttonCoupon, 2, 5, 1, 1);
    gtk_grid_attach(gridPayment, totalbillLabel, 0, 6, 1, 1);
    gtk_grid_attach(gridPayment, moneyTotal, 1, 6, 2, 1);
    gtk_grid_attach(gridPayment, discountLabel, 0, 7, 1, 1);
    gtk_grid_attach(gridPayment, moneyDiscount, 1, 7, 2, 1);
    gtk_grid_attach(gridPayment, costLabel, 0, 8, 1, 1);
    gtk_grid_attach(gridPayment, moneyCost, 1, 8, 2, 1);
    gtk_grid_attach(gridPayment, buttonOrder, 1, 9, 1, 1);
    gtk_widget_set_name(moneyCost, "moneyCost");
    gtk_widget_set_name(moneyDiscount, "moneyDiscount");
    gtk_widget_set_name(moneyTotal, "moneyTotal");
    gtk_widget_set_name(gridPayment, "gridPayment");
    gtk_widget_set_name(buttonOrder, "buttonOrder");
    gtk_container_add(GTK_CONTAINER(window), gridPayment);
    gtk_widget_show_all (window);
}
int main(int argc, char **argv) {
    GtkAllocation *app;
    int status;
    app = gtk_application_new("app.hello",G_APPLICATION_FLAGS_NONE);
    g_signal_connect(app, "activate", G_CALLBACK(activate), NULL);
    status = g_application_run(G_APPLICATION(app), argc, argv);
    g_object_unref(app);
    return status;
}
